C00kie123 update about Page
adxy/chesskhelo.in pull request #7
Opened 2023-01-12 01:13 UTC by c00kie123

2023-01-13 04:44 UTC, adxy commented on pages/about.jsx
> +      can contact the development team by raising an issue request on our Github repository<p>
```suggestion
      can contact the development team by raising an issue request on our GitHub repository</p>
```

2023-01-13 04:45 UTC, adxy commented on pages/about.jsx
> +      in getting involved with the project, you can check out the Github repository for more information on how to contribute<p>
```suggestion
      in getting involved with the project, you can check out the GitHub repository for more information on how to contribute</p>
```

2023-01-13 04:49 UTC, adxy requested changes
Hey @c00kie123, I see that you're missing on closing some <p> tags, I've highlighted those in the code. 

Also, I think you've not setup the code and run it on the local machine. Please do it to make sure the page is linted successfully. 

Read the Readme.md to know how to set it up locally. You might also have to install two vs code plugins - eslint & prettier

2023-01-14 13:08 UTC, c00kie123 commented
Hey, I have made the changes and it is working in my environment

2023-01-15 10:07 UTC, adxy commented
Hey @c00kie123. I will review this in the next 24hrs. I am a little occupied with something today. Thanks for your patience. 😀

2023-01-16 10:08 UTC, adxy approved these changes
There are some formatting issues, I guess you've not successfully set up prettier plugin for vs code. I'll go ahead and accept this as this can be fixed later. Good job, thanks for your contribution! .✨

2023-01-16 10:09 UTC, merged

2023-01-16 10:19 UTC, c00kie123 commented
Hey, what are the formatting issues? I will try it on my environment